global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'whatsapp-gateway-backend'
    static_configs:
      - targets: ['whatsappin-backend:3001']
    metrics_path: '/metrics'
